apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: consul
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - consul-celje.lb.djnd.si
        # - celjepomoje.si
        # - www.celjepomoje.si
      secretName: consul-celje-tls
  rules:
    - host: consul-celje.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: consul
                port:
                  number: 3000
    # - host: celjepomoje.si
    #   http:
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         backend:
    #           service:
    #             name: consul
    #             port:
    #               number: 3000
    # - host: www.celjepomoje.si
    #   http:
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         backend:
    #           service:
    #             name: consul
    #             port:
    #               number: 3000
