apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: consul-ai
resources:
  - database.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: consul
    newName: rg.fr-par.scw.cloud/djnd/consul-ai
    newTag: 'ea8f7a2346759357819d85777c0eacafa9fb1e68'
