apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: consul-staging
resources:
  - database.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: consul
    newName: rg.fr-par.scw.cloud/djnd/consul-staging
    newTag: '5c960cc0b0bada26369ae89cbf4d86d18d11f351'
