apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: consul-ankaran
resources:
  - database.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: consul
    newName: rg.fr-par.scw.cloud/djnd/consul-ankaran
    newTag: 'ee60c4d49c237aa42a72535db459ea40b90c266b'
  # - name: consul-assets
  #   newName: rg.fr-par.scw.cloud/djnd/consul-assets
  #   newTag: 'ee60c4d49c237aa42a72535db459ea40b90c266b'
