require 'date'
load Rails.root.join('app', 'models', 'user.rb')

class User < ApplicationRecord

  validate :emso_number, on: :create
  validate :validate_data_consent, on: :create
  validate :validate_address, on: [:create, :update]
  validates :email, on: :create, presence: true
  
  def validate_data_consent
    unless data_consent
      errors.add(:data_consent, I18n.t('custom.errors.data_consent'))
    end
  end

  def validate_address
    errors.add(:address, I18n.t('activerecord.errors.models.user.attributes.address.invalid')) unless is_valid_address?
  end

  def emso_number
    unless organization
      errors.add(:document_number, I18n.t('activerecord.errors.models.user.attributes.document_number.invalid')) unless valid_emso_number?
    end
  end

  def heading_id
    # Ankaran vzhod
    escaped_addresses = @@valid_addresses_vzhod.map { |valid_address| Regexp.escape(valid_address)}
    r = /^#{escaped_addresses.join("$|^")}$/i # assuming there are no special chars
    if r === address
      return 4
    end

    # Ankaran center
    escaped_addresses = @@valid_addresses_center.map { |valid_address| Regexp.escape(valid_address)}
    r = /^#{escaped_addresses.join("$|^")}$/i # assuming there are no special chars
    if r === address
      return 5
    end

    # Ankaran zahod
    escaped_addresses = @@valid_addresses_zahod.map { |valid_address| Regexp.escape(valid_address)}
    r = /^#{escaped_addresses.join("$|^")}$/i # assuming there are no special chars
    if r === address
      return 3
    end
  end

  def self.date_from_emso(emso)
    if emso[4] == '0'
      Date.parse('2' + emso[4] + emso[5] + emso[6] + '-' + emso[2] + emso[3] + '-' + emso[0] + emso[1])
    else
      Date.parse('1' + emso[4] + emso[5] + emso[6] + '-' + emso[2] + emso[3] + '-' + emso[0] + emso[1])
    end
  end

  def self.is_old_enough(birthday)
    date_limit = Date.parse('2011-01-01') # TODO make this a constant
    if date_limit < birthday
      return false
    end
    true
  end

  def self.valid_emso?(emso)
    if emso.length == 13
      if /[0123]\d[01]\d[09]\d\d\d{6}/.match(emso)
        if emso[12].to_i == 11 - (
        (
        ((emso[0].to_i + emso[6].to_i) * 7) +
          ((emso[1].to_i + emso[7].to_i) * 6) +
          ((emso[2].to_i + emso[8].to_i) * 5) +
          ((emso[3].to_i + emso[9].to_i) * 4) +
          ((emso[4].to_i + emso[10].to_i) * 3) +
          ((emso[5].to_i + emso[11].to_i) * 2)
        ) % 11
        )
          return is_old_enough(date_from_emso(emso))
        elsif emso[12].to_i == (
        ((emso[0].to_i + emso[6].to_i) * 7) +
          ((emso[1].to_i + emso[7].to_i) * 6) +
          ((emso[2].to_i + emso[8].to_i) * 5) +
          ((emso[3].to_i + emso[9].to_i) * 4) +
          ((emso[4].to_i + emso[10].to_i) * 3) +
          ((emso[5].to_i + emso[11].to_i) * 2)
        ) % 11
          return is_old_enough(date_from_emso(emso))
        else
          return false
        end
      end
    end
    false
  end

  @@valid_addresses_vzhod = [
    # Ankaran vzhod
    'Cesta na Prisojo 1',
    'Cesta na Prisojo 1a',
    'Cesta na Prisojo 1b',
    'Cesta na Prisojo 1c',
    'Cesta na Prisojo 1d',
    'Cesta na Prisojo 1e',
    'Cesta na Prisojo 1f',
    'Cesta na Prisojo 1g',
    'Cesta na Prisojo 2',
    'Cesta na Prisojo 3',
    'Cesta na Prisojo 3a',
    'Cesta na Prisojo 4',
    'Cesta na Prisojo 4a',
    'Cesta na Prisojo 5',
    'Cesta na Prisojo 6',
    'Cesta na Prisojo 7',
    'Cesta na Prisojo 9',
    'Ivančičeva cesta 1',
    'Ivančičeva cesta 10',
    'Ivančičeva cesta 10a',
    'Ivančičeva cesta 10b',
    'Ivančičeva cesta 11',
    'Ivančičeva cesta 11c',
    'Ivančičeva cesta 13',
    'Ivančičeva cesta 13a',
    'Ivančičeva cesta 14',
    'Ivančičeva cesta 15',
    'Ivančičeva cesta 15a',
    'Ivančičeva cesta 16',
    'Ivančičeva cesta 17',
    'Ivančičeva cesta 17a',
    'Ivančičeva cesta 17b',
    'Ivančičeva cesta 17c',
    'Ivančičeva cesta 17d',
    'Ivančičeva cesta 18',
    'Ivančičeva cesta 18a',
    'Ivančičeva cesta 19',
    'Ivančičeva cesta 19a',
    'Ivančičeva cesta 19b',
    'Ivančičeva cesta 19c',
    'Ivančičeva cesta 1a',
    'Ivančičeva cesta 2',
    'Ivančičeva cesta 20',
    'Ivančičeva cesta 20a',
    'Ivančičeva cesta 21',
    'Ivančičeva cesta 22',
    'Ivančičeva cesta 24',
    'Ivančičeva cesta 26',
    'Ivančičeva cesta 28',
    'Ivančičeva cesta 2b',
    'Ivančičeva cesta 2d',
    'Ivančičeva cesta 2e',
    'Ivančičeva cesta 2f',
    'Ivančičeva cesta 2g',
    'Ivančičeva cesta 3',
    'Ivančičeva cesta 30',
    'Ivančičeva cesta 32',
    'Ivančičeva cesta 34',
    'Ivančičeva cesta 36',
    'Ivančičeva cesta 3b',
    'Ivančičeva cesta 3c',
    'Ivančičeva cesta 4',
    'Ivančičeva cesta 4b',
    'Ivančičeva cesta 4c',
    'Ivančičeva cesta 4d',
    'Ivančičeva cesta 4e',
    'Ivančičeva cesta 4f',
    'Ivančičeva cesta 5',
    'Ivančičeva cesta 6',
    'Ivančičeva cesta 6a',
    'Ivančičeva cesta 6e',
    'Ivančičeva cesta 7',
    'Ivančičeva cesta 7a',
    'Ivančičeva cesta 7c',
    'Ivančičeva cesta 8',
    'Ivančičeva cesta 9',
    'Jadranska cesta 1',
    'Jadranska cesta 10',
    'Jadranska cesta 11',
    'Jadranska cesta 11a',
    'Jadranska cesta 12',
    'Jadranska cesta 12a',
    'Jadranska cesta 13',
    'Jadranska cesta 14',
    'Jadranska cesta 14a',
    'Jadranska cesta 14b',
    'Jadranska cesta 14c',
    'Jadranska cesta 14d',
    'Jadranska cesta 14e',
    'Jadranska cesta 14f',
    'Jadranska cesta 15',
    'Jadranska cesta 15a',
    'Jadranska cesta 16',
    'Jadranska cesta 16a',
    'Jadranska cesta 16b',
    'Jadranska cesta 16c',
    'Jadranska cesta 16d',
    'Jadranska cesta 16e',
    'Jadranska cesta 16f',
    'Jadranska cesta 17',
    'Jadranska cesta 18',
    'Jadranska cesta 18a',
    'Jadranska cesta 19',
    'Jadranska cesta 19a',
    'Jadranska cesta 1a',
    'Jadranska cesta 2',
    'Jadranska cesta 20',
    'Jadranska cesta 21',
    'Jadranska cesta 21a',
    'Jadranska cesta 21b',
    'Jadranska cesta 21c',
    'Jadranska cesta 21d',
    'Jadranska cesta 22',
    'Jadranska cesta 22a',
    'Jadranska cesta 22d',
    'Jadranska cesta 2a',
    'Jadranska cesta 2b',
    'Jadranska cesta 3',
    'Jadranska cesta 3a',
    'Jadranska cesta 3b',
    'Jadranska cesta 4',
    'Jadranska cesta 4a',
    'Jadranska cesta 4b',
    'Jadranska cesta 4c',
    'Jadranska cesta 4d',
    'Jadranska cesta 5',
    'Jadranska cesta 6',
    'Jadranska cesta 7',
    'Jadranska cesta 8',
    'Jadranska cesta 9',
    'Na Logu 1',
    'Na Logu 10',
    'Na Logu 12',
    'Na Logu 13',
    'Na Logu 13a',
    'Na Logu 14',
    'Na Logu 15',
    'Na Logu 15a',
    'Na Logu 16',
    'Na Logu 17',
    'Na Logu 18',
    'Na Logu 1a',
    'Na Logu 1b',
    'Na Logu 2',
    'Na Logu 3',
    'Na Logu 4',
    'Na Logu 5',
    'Na Logu 7',
    'Na Logu 7a',
    'Na Logu 8',
    'Na Logu 9',
    'Pod vrhom 1',
    'Pod vrhom 1a',
    'Pod vrhom 1b',
    'Pod vrhom 1c',
    'Pod vrhom 1d',
    'Pod vrhom 1e',
    'Pod vrhom 2',
    'Pod vrhom 3',
    'Pod vrhom 4',
    'Pod vrhom 5',
    'Pod vrhom 7',
    'Rožnik 1',
    'Rožnik 10',
    'Rožnik 10a',
    'Rožnik 11',
    'Rožnik 11a',
    'Rožnik 12',
    'Rožnik 13',
    'Rožnik 13a',
    'Rožnik 14',
    'Rožnik 15',
    'Rožnik 16',
    'Rožnik 17',
    'Rožnik 19',
    'Rožnik 2',
    'Rožnik 3',
    'Rožnik 4',
    'Rožnik 5',
    'Rožnik 6',
    'Rožnik 7',
    'Rožnik 8',
    'Rožnik 8a',
    'Rožnik 9',
    'Rožnik 9a',
    'Železniška cesta 1',
    'Železniška cesta 10',
    'Železniška cesta 11',
    'Železniška cesta 13',
    'Železniška cesta 15',
    'Železniška cesta 15b',
    'Železniška cesta 15c',
    'Železniška cesta 15e',
    'Železniška cesta 17',
    'Železniška cesta 17a',
    'Železniška cesta 17b',
    'Železniška cesta 17c',
    'Železniška cesta 19',
    'Železniška cesta 2',
    'Železniška cesta 3',
    'Železniška cesta 4',
    'Železniška cesta 5',
    'Železniška cesta 6',
    'Železniška cesta 7',
    'Železniška cesta 8',
    'Železniška cesta 8a',
    'Železniška cesta 9',
  ]
  @@valid_addresses_zahod = [
    # Ankaran zahod
    'Jadranska cesta 33',
    'Jadranska cesta 33a',
    'Jadranska cesta 35',
    'Jadranska cesta 35a',
    'Jadranska cesta 35b',
    'Jadranska cesta 37a',
    'Jadranska cesta 37b',
    'Jadranska cesta 39',
    'Jadranska cesta 39a',
    'Jadranska cesta 39b',
    'Jadranska cesta 39c',
    'Jadranska cesta 39d',
    'Jadranska cesta 41',
    'Jadranska cesta 41a',
    'Jadranska cesta 43',
    'Jadranska cesta 45',
    'Jadranska cesta 45a',
    'Jadranska cesta 45b',
    'Jadranska cesta 45c',
    'Jadranska cesta 45d',
    'Jadranska cesta 45e',
    'Jadranska cesta 45f',
    'Jadranska cesta 45g',
    'Jadranska cesta 45h',
    'Jadranska cesta 47',
    'Jadranska cesta 47a',
    'Jadranska cesta 47b',
    'Jadranska cesta 47c',
    'Jadranska cesta 47d',
    'Jadranska cesta 47e',
    'Jadranska cesta 47f',
    'Jadranska cesta 47g',
    'Jadranska cesta 47h',
    'Jadranska cesta 47i',
    'Jadranska cesta 47j',
    'Jadranska cesta 49',
    'Jadranska cesta 49a',
    'Jadranska cesta 49b',
    'Jadranska cesta 51',
    'Jadranska cesta 51a',
    'Jadranska cesta 51b',
    'Jadranska cesta 51c',
    'Jadranska cesta 51d',
    'Jadranska cesta 51e',
    'Jadranska cesta 51f',
    'Jadranska cesta 51g',
    'Jadranska cesta 59',
    'Jadranska cesta 59a',
    'Jadranska cesta 59b',
    'Jadranska cesta 59c',
    'Jadranska cesta 59d',
    'Jadranska cesta 61',
    'Jadranska cesta 61a',
    'Jadranska cesta 61b',
    'Jadranska cesta 63',
    'Jadranska cesta 65',
    'Jadranska cesta 67',
    'Jadranska cesta 69',
    'Jadranska cesta 71',
    'Jadranska cesta 73',
    'Jadranska cesta 73a',
    'Jadranska cesta 75',
    'Jadranska cesta 77',
    'Jadranska cesta 79',
    'Jadranska cesta 81',
    'Jadranska cesta 83',
    'Jadranska cesta 85',
    'Jadranska cesta 85a',
    'Jadranska cesta 86',
    'Jadranska cesta 88',
    'Jadranska cesta 90',
    'Jadranska cesta 92',
    'Jadranska cesta 94',
    'Jadranska cesta 96',
    'Lazaret 1',
    'Lazaret 2',
    'Lazaret 4',
    'Lazaret 4a',
    'Lazaret 5',
    'Lazaret 6',
    'Lazaret 6a',
    'Lazaret 6b',
    'Lazaret 7',
    'Lazaret 8',
    'Razgledna pot 1',
    'Vinogradniška pot 10',
    'Vinogradniška pot 11',
    'Vinogradniška pot 11a',
    'Vinogradniška pot 12',
    'Vinogradniška pot 13',
    'Vinogradniška pot 14',
    'Vinogradniška pot 15',
    'Vinogradniška pot 15a',
    'Vinogradniška pot 15b',
    'Vinogradniška pot 15c',
    'Vinogradniška pot 15d',
    'Vinogradniška pot 15e',
    'Vinogradniška pot 15f',
    'Vinogradniška pot 15g',
    'Vinogradniška pot 16',
    'Vinogradniška pot 17',
    'Vinogradniška pot 18',
    'Vinogradniška pot 19',
    'Vinogradniška pot 2',
    'Vinogradniška pot 20',
    'Vinogradniška pot 21',
    'Vinogradniška pot 21a',
    'Vinogradniška pot 22',
    'Vinogradniška pot 23',
    'Vinogradniška pot 24',
    'Vinogradniška pot 25',
    'Vinogradniška pot 27',
    'Vinogradniška pot 27a',
    'Vinogradniška pot 29',
    'Vinogradniška pot 3',
    'Vinogradniška pot 31',
    'Vinogradniška pot 33',
    'Vinogradniška pot 35',
    'Vinogradniška pot 3a',
    'Vinogradniška pot 4',
    'Vinogradniška pot 5',
    'Vinogradniška pot 6',
    'Vinogradniška pot 7',
    'Vinogradniška pot 7a',
    'Vinogradniška pot 7b',
    'Vinogradniška pot 8',
    'Vinogradniška pot 9',
  ]
  @@valid_addresses_center = [
    # Ankaran center
    'Bertokova ulica 1',
    'Bertokova ulica 10',
    'Bertokova ulica 11',
    'Bertokova ulica 12',
    'Bertokova ulica 13',
    'Bertokova ulica 14',
    'Bertokova ulica 15',
    'Bertokova ulica 16',
    'Bertokova ulica 17',
    'Bertokova ulica 2',
    'Bertokova ulica 3',
    'Bertokova ulica 4',
    'Bertokova ulica 5',
    'Bertokova ulica 6',
    'Bertokova ulica 7',
    'Bertokova ulica 8',
    'Bertokova ulica 9',
    'Bevkova ulica 1',
    'Bevkova ulica 10',
    'Bevkova ulica 11',
    'Bevkova ulica 12',
    'Bevkova ulica 13',
    'Bevkova ulica 14',
    'Bevkova ulica 15',
    'Bevkova ulica 16',
    'Bevkova ulica 17',
    'Bevkova ulica 18',
    'Bevkova ulica 19',
    'Bevkova ulica 19a',
    'Bevkova ulica 2',
    'Bevkova ulica 20',
    'Bevkova ulica 21',
    'Bevkova ulica 22',
    'Bevkova ulica 23',
    'Bevkova ulica 24',
    'Bevkova ulica 25',
    'Bevkova ulica 26',
    'Bevkova ulica 27',
    'Bevkova ulica 28',
    'Bevkova ulica 29',
    'Bevkova ulica 3',
    'Bevkova ulica 30',
    'Bevkova ulica 31',
    'Bevkova ulica 32',
    'Bevkova ulica 33',
    'Bevkova ulica 34',
    'Bevkova ulica 35',
    'Bevkova ulica 36',
    'Bevkova ulica 37',
    'Bevkova ulica 38',
    'Bevkova ulica 39',
    'Bevkova ulica 4',
    'Bevkova ulica 40',
    'Bevkova ulica 41',
    'Bevkova ulica 42',
    'Bevkova ulica 43',
    'Bevkova ulica 44',
    'Bevkova ulica 45',
    'Bevkova ulica 46',
    'Bevkova ulica 48',
    'Bevkova ulica 5',
    'Bevkova ulica 50',
    'Bevkova ulica 52',
    'Bevkova ulica 54',
    'Bevkova ulica 56',
    'Bevkova ulica 58',
    'Bevkova ulica 6',
    'Bevkova ulica 7',
    'Bevkova ulica 8',
    'Bevkova ulica 9',
    'Cahova ulica 1',
    'Cahova ulica 10',
    'Cahova ulica 11',
    'Cahova ulica 12',
    'Cahova ulica 14',
    'Cahova ulica 2',
    'Cahova ulica 3',
    'Cahova ulica 4',
    'Cahova ulica 5',
    'Cahova ulica 6',
    'Cahova ulica 7',
    'Cahova ulica 7a',
    'Cahova ulica 8',
    'Cahova ulica 9',
    'Frenkova ulica 1',
    'Frenkova ulica 10',
    'Frenkova ulica 11',
    'Frenkova ulica 12',
    'Frenkova ulica 13',
    'Frenkova ulica 14',
    'Frenkova ulica 15',
    'Frenkova ulica 16',
    'Frenkova ulica 17',
    'Frenkova ulica 18',
    'Frenkova ulica 19',
    'Frenkova ulica 2',
    'Frenkova ulica 21',
    'Frenkova ulica 23',
    'Frenkova ulica 24',
    'Frenkova ulica 25',
    'Frenkova ulica 3',
    'Frenkova ulica 4',
    'Frenkova ulica 5',
    'Frenkova ulica 6',
    'Frenkova ulica 7',
    'Frenkova ulica 8',
    'Frenkova ulica 9',
    'Hrvatinova ulica 1',
    'Hrvatinova ulica 10',
    'Hrvatinova ulica 11',
    'Hrvatinova ulica 12',
    'Hrvatinova ulica 13',
    'Hrvatinova ulica 14',
    'Hrvatinova ulica 15',
    'Hrvatinova ulica 16',
    'Hrvatinova ulica 17',
    'Hrvatinova ulica 18',
    'Hrvatinova ulica 19',
    'Hrvatinova ulica 2',
    'Hrvatinova ulica 20',
    'Hrvatinova ulica 22',
    'Hrvatinova ulica 24',
    'Hrvatinova ulica 2a',
    'Hrvatinova ulica 2b',
    'Hrvatinova ulica 3',
    'Hrvatinova ulica 4',
    'Hrvatinova ulica 6',
    'Hrvatinova ulica 7',
    'Hrvatinova ulica 8',
    'Hrvatinova ulica 8a',
    'Hrvatinova ulica 9',
    'Jadranska cesta 25',
    'Jadranska cesta 27',
    'Jadranska cesta 29',
    'Jadranska cesta 31',
    'Jadranska cesta 31a',
    'Jadranska cesta 42',
    'Jadranska cesta 46',
    'Jadranska cesta 48',
    'Jadranska cesta 50',
    'Jadranska cesta 52',
    'Jadranska cesta 54',
    'Jadranska cesta 56',
    'Jadranska cesta 58',
    'Jadranska cesta 60',
    'Jadranska cesta 60a',
    'Jadranska cesta 62',
    'Jadranska cesta 64',
    'Jadranska cesta 64a',
    'Jadranska cesta 64b',
    'Jadranska cesta 64c',
    'Jadranska cesta 66',
    'Jadranska cesta 66a',
    'Jadranska cesta 68',
    'Jadranska cesta 68a',
    'Jadranska cesta 70',
    'Jadranska cesta 72',
    'Jadranska cesta 74',
    'Jadranska cesta 76',
    'Jadranska cesta 76a',
    'Jadranska cesta 78',
    'Jadranska cesta 80',
    'Jadranska cesta 82',
    'Jadranska cesta 84',
    'Jadranska cesta 86a',
    'Kocjančičeva ulica 1',
    'Kocjančičeva ulica 10',
    'Kocjančičeva ulica 11',
    'Kocjančičeva ulica 12',
    'Kocjančičeva ulica 13',
    'Kocjančičeva ulica 14',
    'Kocjančičeva ulica 15',
    'Kocjančičeva ulica 16',
    'Kocjančičeva ulica 17',
    'Kocjančičeva ulica 18',
    'Kocjančičeva ulica 19',
    'Kocjančičeva ulica 2',
    'Kocjančičeva ulica 20',
    'Kocjančičeva ulica 21',
    'Kocjančičeva ulica 22',
    'Kocjančičeva ulica 23',
    'Kocjančičeva ulica 24',
    'Kocjančičeva ulica 25',
    'Kocjančičeva ulica 26',
    'Kocjančičeva ulica 27',
    'Kocjančičeva ulica 28',
    'Kocjančičeva ulica 29',
    'Kocjančičeva ulica 3',
    'Kocjančičeva ulica 30',
    'Kocjančičeva ulica 31',
    'Kocjančičeva ulica 32',
    'Kocjančičeva ulica 33',
    'Kocjančičeva ulica 34',
    'Kocjančičeva ulica 35',
    'Kocjančičeva ulica 36',
    'Kocjančičeva ulica 37',
    'Kocjančičeva ulica 38',
    'Kocjančičeva ulica 39',
    'Kocjančičeva ulica 4',
    'Kocjančičeva ulica 40',
    'Kocjančičeva ulica 41',
    'Kocjančičeva ulica 5',
    'Kocjančičeva ulica 6',
    'Kocjančičeva ulica 7',
    'Kocjančičeva ulica 8',
    'Kocjančičeva ulica 9',
    'Larisova ulica 1',
    'Larisova ulica 10',
    'Larisova ulica 11',
    'Larisova ulica 12',
    'Larisova ulica 13',
    'Larisova ulica 14',
    'Larisova ulica 15',
    'Larisova ulica 16',
    'Larisova ulica 1a',
    'Larisova ulica 2',
    'Larisova ulica 3',
    'Larisova ulica 4',
    'Larisova ulica 5',
    'Larisova ulica 6',
    'Larisova ulica 7',
    'Larisova ulica 8',
    'Larisova ulica 9',
    'Oljčna pot 1',
    'Oljčna pot 10',
    'Oljčna pot 11',
    'Oljčna pot 12',
    'Oljčna pot 12a',
    'Oljčna pot 13',
    'Oljčna pot 14',
    'Oljčna pot 15',
    'Oljčna pot 16',
    'Oljčna pot 17',
    'Oljčna pot 18',
    'Oljčna pot 19',
    'Oljčna pot 2',
    'Oljčna pot 20',
    'Oljčna pot 20a',
    'Oljčna pot 21',
    'Oljčna pot 22',
    'Oljčna pot 23',
    'Oljčna pot 24',
    'Oljčna pot 3',
    'Oljčna pot 4',
    'Oljčna pot 5',
    'Oljčna pot 6',
    'Oljčna pot 7',
    'Oljčna pot 7a',
    'Oljčna pot 8',
    'Oljčna pot 8a',
    'Oljčna pot 8b',
    'Oljčna pot 8c',
    'Oljčna pot 9',
    'Pervanjeva ulica 10',
    'Pervanjeva ulica 12',
    'Pervanjeva ulica 14',
    'Pervanjeva ulica 16',
    'Pervanjeva ulica 18',
    'Pervanjeva ulica 2',
    'Pervanjeva ulica 4',
    'Pervanjeva ulica 6',
    'Pervanjeva ulica 8',
    'Pot na Brido 1',
    'Pot na Brido 10',
    'Pot na Brido 1a',
    'Pot na Brido 1b',
    'Pot na Brido 2',
    'Pot na Brido 2a',
    'Pot na Brido 2b',
    'Pot na Brido 2c',
    'Pot na Brido 3',
    'Pot na Brido 3b',
    'Pot na Brido 3c',
    'Pot na Brido 4',
    'Pot na Brido 4a',
    'Pot na Brido 4c',
    'Pot na Brido 4d',
    'Pot na Brido 4e',
    'Pot na Brido 4f',
    'Pot na Brido 5',
    'Pot na Brido 6',
    'Pot na Brido 6d',
    'Pot na Brido 6e',
    'Pot na Brido 6f',
    'Pot na Brido 6g',
    'Pot na Brido 8',
    'Pot na Brido 8a',
    'Pot na Brido 8b',
    'Pot na Brido 8c',
    'Pot na Brido 8d',
    'Razgledna pot 10',
    'Razgledna pot 11',
    'Razgledna pot 11a',
    'Razgledna pot 11b',
    'Razgledna pot 11c',
    'Razgledna pot 11d',
    'Razgledna pot 12',
    'Razgledna pot 13',
    'Razgledna pot 13a',
    'Razgledna pot 14',
    'Razgledna pot 15',
    'Razgledna pot 16',
    'Razgledna pot 16a',
    'Razgledna pot 16b',
    'Razgledna pot 17',
    'Razgledna pot 18',
    'Razgledna pot 19',
    'Razgledna pot 2',
    'Razgledna pot 20',
    'Razgledna pot 21',
    'Razgledna pot 22',
    'Razgledna pot 24',
    'Razgledna pot 26',
    'Razgledna pot 2a',
    'Razgledna pot 2b',
    'Razgledna pot 2c',
    'Razgledna pot 2d',
    'Razgledna pot 3',
    'Razgledna pot 4',
    'Razgledna pot 5',
    'Razgledna pot 5a',
    'Razgledna pot 6',
    'Razgledna pot 7',
    'Razgledna pot 8',
    'Razgledna pot 8a',
    'Razgledna pot 9',
    'Regentova ulica 1',
    'Regentova ulica 10',
    'Regentova ulica 2',
    'Regentova ulica 2a',
    'Regentova ulica 2b',
    'Regentova ulica 3',
    'Regentova ulica 4',
    'Regentova ulica 4a',
    'Regentova ulica 4b',
    'Regentova ulica 4c',
    'Regentova ulica 6',
    'Regentova ulica 8',
    'Srebrničeva ulica 1',
    'Srebrničeva ulica 11',
    'Srebrničeva ulica 13',
    'Srebrničeva ulica 15',
    'Srebrničeva ulica 3',
    'Srebrničeva ulica 5',
    'Srebrničeva ulica 7',
    'Tomažičeva ulica 1',
    'Tomažičeva ulica 10',
    'Tomažičeva ulica 11',
    'Tomažičeva ulica 12',
    'Tomažičeva ulica 13',
    'Tomažičeva ulica 14',
    'Tomažičeva ulica 15',
    'Tomažičeva ulica 2',
    'Tomažičeva ulica 3',
    'Tomažičeva ulica 4',
    'Tomažičeva ulica 5',
    'Tomažičeva ulica 6',
    'Tomažičeva ulica 7',
    'Tomažičeva ulica 8',
    'Tomažičeva ulica 9',
    'Ulica Rudija Mahniča 1',
    'Ulica Rudija Mahniča 10',
    'Ulica Rudija Mahniča 11',
    'Ulica Rudija Mahniča 12',
    'Ulica Rudija Mahniča 2',
    'Ulica Rudija Mahniča 2a',
    'Ulica Rudija Mahniča 3',
    'Ulica Rudija Mahniča 4',
    'Ulica Rudija Mahniča 5',
    'Ulica Rudija Mahniča 6',
    'Ulica Rudija Mahniča 7',
    'Ulica Rudija Mahniča 8',
    'Ulica Rudija Mahniča 9',
    'Vlahovičeva ulica 1',
    'Vlahovičeva ulica 10',
    'Vlahovičeva ulica 11',
    'Vlahovičeva ulica 12',
    'Vlahovičeva ulica 13',
    'Vlahovičeva ulica 14',
    'Vlahovičeva ulica 15',
    'Vlahovičeva ulica 16',
    'Vlahovičeva ulica 17',
    'Vlahovičeva ulica 18',
    'Vlahovičeva ulica 18a',
    'Vlahovičeva ulica 19',
    'Vlahovičeva ulica 2',
    'Vlahovičeva ulica 20',
    'Vlahovičeva ulica 21',
    'Vlahovičeva ulica 22',
    'Vlahovičeva ulica 23',
    'Vlahovičeva ulica 24',
    'Vlahovičeva ulica 25',
    'Vlahovičeva ulica 26',
    'Vlahovičeva ulica 27',
    'Vlahovičeva ulica 28',
    'Vlahovičeva ulica 29',
    'Vlahovičeva ulica 3',
    'Vlahovičeva ulica 30',
    'Vlahovičeva ulica 31',
    'Vlahovičeva ulica 32',
    'Vlahovičeva ulica 33',
    'Vlahovičeva ulica 34',
    'Vlahovičeva ulica 35',
    'Vlahovičeva ulica 36',
    'Vlahovičeva ulica 37',
    'Vlahovičeva ulica 38',
    'Vlahovičeva ulica 39',
    'Vlahovičeva ulica 4',
    'Vlahovičeva ulica 40',
    'Vlahovičeva ulica 41',
    'Vlahovičeva ulica 42',
    'Vlahovičeva ulica 43',
    'Vlahovičeva ulica 44',
    'Vlahovičeva ulica 45',
    'Vlahovičeva ulica 46',
    'Vlahovičeva ulica 47',
    'Vlahovičeva ulica 48',
    'Vlahovičeva ulica 49',
    'Vlahovičeva ulica 5',
    'Vlahovičeva ulica 50',
    'Vlahovičeva ulica 51',
    'Vlahovičeva ulica 52',
    'Vlahovičeva ulica 53',
    'Vlahovičeva ulica 54',
    'Vlahovičeva ulica 55',
    'Vlahovičeva ulica 56',
    'Vlahovičeva ulica 57',
    'Vlahovičeva ulica 58',
    'Vlahovičeva ulica 59',
    'Vlahovičeva ulica 6',
    'Vlahovičeva ulica 61',
    'Vlahovičeva ulica 63',
    'Vlahovičeva ulica 65',
    'Vlahovičeva ulica 67',
    'Vlahovičeva ulica 69',
    'Vlahovičeva ulica 7',
    'Vlahovičeva ulica 71',
    'Vlahovičeva ulica 8',
    'Vlahovičeva ulica 9',
  ]

  private

  def valid_emso_number?
    if (Rails.env.development? && email == 'admin@consul.dev') || Rails.env.test?
      return true
    end
    User.valid_emso?(document_number)
  end

  # regex check if address is valid
  def is_valid_address?
    valid_addresses = @@valid_addresses_vzhod + @@valid_addresses_zahod + @@valid_addresses_center
    escaped_addresses = valid_addresses.map { |valid_address| Regexp.escape(valid_address)}
    r = /^#{escaped_addresses.join("$|^")}$/i # assuming there are no special chars
    return r === address
  end
end
